name: Generate Protos

on:
  workflow_dispatch: {}

jobs:
  gen-protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - name: Generate protos
        run: |
          ./tool/gen_protos.sh /tmp/fabric-protos
      - name: Check for changes
        run: |
          git status --porcelain
